global:
    scrape_interval: 15s

    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: 'kafka-monitor'

scrape_configs:
    - job_name: 'kafka-controller'

      scrape_interval: 5s

      static_configs:
        - targets:
            - controller-1:8091
            - controller-2:8091
            - controller-3:8091
    - job_name: 'kafka-broker'

      scrape_interval: 5s

      static_configs:
        - targets:
            - kafka-1:8091
            - kafka-2:8091
            - kafka-3:8091
